### ISSUE TITLE
해결해야할 문제들

### ISSUE THREAD

**Issue by keonwoo98** [42-TRANSENDENCE/frontend#16]
- [x] 2FA 상태값 업데이트 에러
- [x] 2FA 6digits 잘못입력 시 input 창 clear, password reset
- [x] GET -> useQuery / PUT, POST, DELETE -> useMutation
- [x] fetcher 만들기
- [x] accessToken 만료 시 refreshToken으로 새로 발급
- [x] AWS에 Front를 Docker로 올려놓기 (현재 npm run dev로 올려놓은 상태, npm run build는 nginx 이슈로 안올라감)
- [x] custom hook으로 기능 분리하기
- [x] Component 분리하기

**Comment by u-lo-l** [comment]
ㅜㅜ 내일 같이 알아봅시다

**Comment by keonwoo98** [comment]
저는 클터에서 밤샘이니 쉬고 편하게 나오십셩ㅠㅠ

**Comment by u-lo-l** [comment]
- [ ] 디자인 다시
- [ ] 게임 페이지와 플레이 페이지에서 유저 정보 가져오기
- [ ] 3D??
- [ ] CrazyMode추가 
================================================
- [ ] 다른 페이지와 겹치는 부분 : 사용자 프로필

**Comment by teetee6** [comment]
- [ ] 디자인 다시
- [ ] 방장 방 나가면 방폭파 되는거 확인하기..?

**Comment by teetee6** [comment]
<img width="1440" alt="스크린샷 2023-03-18 오후 11 49 14" src="https://user-images.githubusercontent.com/17748068/226113296-d7338403-6c06-4cf9-ac3d-1c05e9c3a6da.png">

함께 작업했던 배경 우측하단 삼각형이 크롬기반 브라우저에선 이렇게 보이네요

**Comment by keonwoo98** [comment]
> <img alt="스크린샷 2023-03-18 오후 11 49 14" width="1440" src="https://user-images.githubusercontent.com/17748068/226113296-d7338403-6c06-4cf9-ac3d-1c05e9c3a6da.png">
> 
> 함께 작업했던 배경 우측하단 삼각형이 크롬기반 브라우저에선 이렇게 보이네요

이건 App.tsx에서 `<AppContainer>` 주석하니까 밑에 잘 붙더라구요
